### ISSUE TITLE
Page Controll无效。

### ISSUE THREAD

**Issue by lhr000lhr** [CoderJackyHuang/HYBLoopScrollView#1]
Page Controll在点击的时候，选中的过去了，图片没有变换。

**Comment by CoderJackyHuang** [comment]
Thank you for your feedback. I didn't handle it when a page control was clicked.I will fix it later. Thanks again.

在 2015-04-03 10:19:13，"lhr000lhr" notifications@github.com 写道：

Page Controll在点击的时候，选中的过去了，图片没有变换。

**Comment by CoderJackyHuang** [comment]
Thank you for your feedback. I didn't handle it when a page control was clicked.I will fix it later. Thanks again.
