### ISSUE TITLE
大哥，你这个库用的afn版本和HYBNetworking里面的不一样

### ISSUE THREAD

**Issue by gdfyj90** [CoderJackyHuang/HYBLoopScrollView#10]
好像不是3.0的？UIImageView+AFNetworking这个文件里面的方法不一样了

**Comment by CoderJackyHuang** [comment]
这个没有支持AFN3.0，是基于2.5的，不过下一版本会去掉AFN，直接使用原生的来下载。另外下一版本去增加多样式。AFN这个版本变化太大了，计划去掉。

原始邮件
发件人:gdfyj90notifications@github.com
收件人:CoderJackyHuang/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
发送时间:2016年3月2日(周三) 17:27
主题:[HYBLoopScrollView] 大哥，你这个库用的afn版本和HYBNetworking里面的不一样 (#10)

好像不是3.0的？UIImageView+AFNetworking这个文件里面的方法不一样了

**Comment by CoderJackyHuang** [comment]
我将去掉AFN，直接使用原生的下载图片！

**Comment by CoderJackyHuang** [comment]
已更新至3.0版本，去掉了AFNetworking的依赖库，直接使用原生下载API！请更新至最新的代码！
