### ISSUE TITLE
标哥代码写的很漂亮，但最终HYBLoopScrollView没有释放

### ISSUE THREAD

**Issue by huaiyongtai** [CoderJackyHuang/HYBLoopScrollView#11]
Timer对HYBLoopScrollView有一个引用，导致HYTLoopView从父控件移除后，仍然没有释放。建议在pauseTimer方法移除Timer

**Comment by CoderJackyHuang** [comment]
我计划下一版本去掉AFN，所以先下一版本会去fix掉。

**Comment by huaiyongtai** [comment]
AFN有问题吗？

**Comment by CoderJackyHuang** [comment]
没有问题，我不希望这个库依赖任何第三方，不然因为AFN版本不同会出现很多问题

原始邮件
发件人:无法修盖notifications@github.com
收件人:CoderJackyHuang/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
抄送:JackyHuang18675574495@163.com
发送时间:2016年3月23日(周三) 17:44
主题:Re: [HYBLoopScrollView] 标哥代码写的很漂亮，但最终HYBLoopScrollView没有释放 (#11)

AFN有问题吗？
  在 2016年3月23日，下午5:41，JackyHuang notifications@github.com 写道：

  我计划下一版本去掉AFN，所以先下一版本会去fix掉。

**Comment by huaiyongtai** [comment]
嗯。标哥牛，搞定了让我看看。哈哈

**Comment by CoderJackyHuang** [comment]
已更新至3.0版本，去掉了AFNetworking的依赖库，直接使用原生下载API！另外你所说的内存得不到释放是你使用的原因的。注意在block回调处要使用弱引用self，不然会得不到释放！已测试过！
