### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xiuqiao** [CoderJackyHuang/HYBLoopScrollView#12]
如果传入imageUrls 数组个数为0或空，奔溃。创建cell 时NSInteger itemIndex = indexPath.item % self.imageUrls.count;

**Comment by CoderJackyHuang** [comment]
请问是最新版本？这个bug是在老版本有的！

**Comment by xiuqiao** [comment]
谢谢，没注意版本号，是老版本

**Comment by CoderJackyHuang** [comment]
已更新至3.0版本，去掉了AFNetworking的依赖库，直接使用原生下载API！
