### ISSUE TITLE
3.1.4 图片上下有灰变，3.0.0没有这种情况

### ISSUE THREAD

**Issue by WLZJ** [CoderJackyHuang/HYBLoopScrollView#17]
<img width="350" alt="2016-04-11 1 28 05" src="https://cloud.githubusercontent.com/assets/13882638/14417524/43228b8e-ffe9-11e5-9ee9-d0974ebff768.png">

**Comment by WLZJ** [comment]
灰边

**Comment by CoderJackyHuang** [comment]
能把代码放出来吗，因为我demo里并没有出现，所以我不知道你做了哪些设置导致的！

**Comment by CoderJackyHuang** [comment]
你是否设置shouldAutoClipImageToViewSize这个属性？

**Comment by WLZJ** [comment]
<img width="913" alt="2016-04-12 10 29 33" src="https://cloud.githubusercontent.com/assets/13882638/14448249/7df1f73a-0099-11e6-9bda-4d07d33bf844.png">
最后，我的解决方案，适配一下透视图的高度

**Comment by WLZJ** [comment]
loop.shouldAutoClipImageToViewSize = NO;
图片就会被剪切的，显示不全！
现在，能不能不让图片不被剪切，而是拉伸，布满控件？

**Comment by CoderJackyHuang** [comment]
设置imgContentModel属性，同时关闭图片剪裁！

原始邮件
发件人:WLZJnotifications@github.com
收件人:CoderJackyHuang/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
抄送:JackyHuang18675574495@163.com
发送时间:2016年4月12日(周二) 10:33
主题:Re: [CoderJackyHuang/HYBLoopScrollView] 3.1.4 图片上下有灰变，3.0.0没有这种情况 (#17)

loop.shouldAutoClipImageToViewSize = NO;
 图片就会被剪切的，显示不全！
 现在，能不能不让图片不被剪切，而是拉伸，布满控件？

**Comment by WLZJ** [comment]
问题解决了，谢谢
