### ISSUE TITLE
出现这个问题是什么原因呢

### ISSUE THREAD

**Issue by changeCh** [CoderJackyHuang/HYBLoopScrollView#18]
the behavior of the UICollectionViewFlowLayout is not defined because:
 the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x7fe208dbd940>, and it is attached to <UICollectionView: 0x7fe2098c7600; frame = (0 0; 414 180); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x7fe208dbed40>; layer = <CALayer: 0x7fe208d26150>; contentOffset: {0, 0}; contentSize: {0, 0}> collection view layout: <UICollectionViewFlowLayout: 0x7fe208dbd940>.
 Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.

**Comment by CoderJackyHuang** [comment]
这个有出现异常吗？

原始邮件
发件人:changeChnotifications@github.com
收件人:CoderJackyHuang/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
发送时间:2016年4月13日(周三) 15:27
主题:[CoderJackyHuang/HYBLoopScrollView] 出现这个问题是什么原因呢 (#18)

the behavior of the UICollectionViewFlowLayout is not defined because:
 the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
 The relevant UICollectionViewFlowLayout instance is , and it is attached to ; layer = ; contentOffset: {0, 0}; contentSize: {0, 0} collection view layout: .
 Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.

**Comment by changeCh** [comment]
额，就是image向上移了一点，大概是pagecontroller的高度

**Comment by CoderJackyHuang** [comment]
这不清楚是哪里被修改。代码是怎么写的？

**Comment by changeCh** [comment]
// 这个图片会找不到，而显示默认图
    NSString *url = @"http://test.meirongzongjian.com/imageServer/user/3/42ccb9c75ccf5e910cd6f5aaf0cd1200.jpg";
    NSArray *images = @[@"http://7xrs9h.com1.z0.glb.clouddn.com/wp-content/uploads/2016/03/QQ20160322-0@2x.png",[UIImage imageNamed:@"首页_02"],
                        @"http://s0.pimg.cn/group6/M00/45/84/wKgBjVZVjYCAEIM4AAKYJZIpvWo152.jpg?imageMogr2/strip/thumbnail/1200%3E/quality/95",
                        url,
                        ];

```
// 请使用weakSelf，不然内存得不到释放
__weak __typeof(self) weakSelf = self;
_loop = [HYBLoopScrollView loopScrollViewWithFrame:CGRectMake(0,0,kWidth,180) imageUrls:images timeInterval:2  didSelect:^(NSInteger atIndex) {
    [weakSelf dismissViewControllerAnimated:YES completion:NULL];
} didScroll:^(NSInteger toIndex) {

}];
_loop.shouldAutoClipImageToViewSize = NO;
_loop.placeholder = [UIImage imageNamed:@"首页_02"];
_loop.alignment = kPageControlAlignCenter;

[self.view addSubview:_loop];

[_loop mas_makeConstraints:^(MASConstraintMaker *make) {
    make.left.right.mas_equalTo(0);
    make.height.mas_equalTo(180);
    make.top.mas_equalTo(0);
}];
_loop.pageControl.currentPageIndicatorTintColor = KsysY;
_loop.pageControl.pageIndicatorTintColor = [UIColor whiteColor];
_loop.imageContentMode = UIViewContentModeScaleAspectFill;
[_loop clearImagesCache];
```

**Comment by CoderJackyHuang** [comment]
图片下载失败当然就会显示默认图！

原始邮件
发件人:changeChnotifications@github.com
收件人:CoderJackyHuang/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
抄送:JackyHuang18675574495@163.com
发送时间:2016年4月18日(周一) 14:15
主题:Re: [CoderJackyHuang/HYBLoopScrollView] 出现这个问题是什么原因呢 (#18)

// 这个图片会找不到，而显示默认图
 NSString *url = @"http://test.meirongzongjian.com/imageServer/user/3/42ccb9c75ccf5e910cd6f5aaf0cd1200.jpg";
 NSArray *images = @[@"http://7xrs9h.com1.z0.glb.clouddn.com/wp-content/uploads/2016/03/QQ20160322-0@2x.png",[UIImage imageNamed:@"首页_02"],
 @"http://s0.pimg.cn/group6/M00/45/84/wKgBjVZVjYCAEIM4AAKYJZIpvWo152.jpg?imageMogr2/strip/thumbnail/1200%3E/quality/95",
 url,
 ];
// 请使用weakSelf，不然内存得不到释放 __weak __typeof(self) weakSelf = self; _loop = [HYBLoopScrollView loopScrollViewWithFrame:CGRectMake(0,0,kWidth,180) imageUrls:images timeInterval:2 didSelect:^(NSInteger atIndex) { [weakSelf dismissViewControllerAnimated:YES completion:NULL]; } didScroll:^(NSInteger toIndex) { }]; _loop.shouldAutoClipImageToViewSize = NO; _loop.placeholder = [UIImage imageNamed:@"首页_02"]; _loop.alignment = kPageControlAlignCenter; [self.view addSubview:_loop]; [_loop mas_makeConstraints:^(MASConstraintMaker *make) { make.left.right.mas_equalTo(0); make.height.mas_equalTo(180); make.top.mas_equalTo(0); }]; _loop.pageControl.currentPageIndicatorTintColor = KsysY; _loop.pageControl.pageIndicatorTintColor = [UIColor whiteColor]; _loop.imageContentMode = UIViewContentModeScaleAspectFill; [_loop clearImagesCache];

**Comment by changeCh** [comment]
。。。。。那个是你写的注释，我直接拷贝上去的，。。

**Comment by changeCh** [comment]
[http://www.bubuko.com/infodetail-1151242.html](url)

**Comment by changeCh** [comment]
[http://www.bubuko.com/infodetail-1151242.html](url)

**Comment by CoderJackyHuang** [comment]
那是我故意写的demo！

原始邮件
发件人:changeChnotifications@github.com
收件人:CoderJackyHuang/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
抄送:JackyHuang18675574495@163.com
发送时间:2016年4月19日(周二) 16:36
主题:Re: [CoderJackyHuang/HYBLoopScrollView] 出现这个问题是什么原因呢 (#18)

http://www.bubuko.com/infodetail-1151242.html
