### ISSUE TITLE
图片在切换时有时会先显示一下背景, 然后在显示图片, 请问是什么原因呢 ?

### ISSUE THREAD

**Issue by lizunshan** [CoderJackyHuang/HYBLoopScrollView#19]
图片在切换时有时会先显示一下背景, 然后在显示图片, 请问是什么原因呢 ?

**Comment by CoderJackyHuang** [comment]
背景？是指占位图片吗？

**Comment by lizunshan** [comment]
嗯, 是的,  第一次启动时,每张图, 会这样显示一圈后正常,   但有时切换一下controller, 在切回来时, 又会每张先显示占位图, 在显示图片

**Comment by lizunshan** [comment]
升级到最新版本, 已解决
