### ISSUE TITLE
为什么我下载demo运行时出错

### ISSUE THREAD

**Issue by huangyunjin** [CoderJackyHuang/HYBLoopScrollView#2]
viewController 中  loop.didSelectItemBlock = ^(NSInteger atIndex) {  };
这几个block显示是错误的

**Comment by CoderJackyHuang** [comment]
这个我的很多朋友都在使用的，都没有出现您说的问题。
如果真的出现这个问题，请看看这个didSelectItemBlock是否有声明，也许是代码不是最新的。
重新下载一份最新的代码
