### ISSUE TITLE
在tabVC中的navVC中的VC遇到了问题

### ISSUE THREAD

**Issue by smileat** [CoderJackyHuang/HYBLoopScrollView#20]
因为我需要滚动栏从状态栏开始，所以按照你的设置了self.edgesForExtendedLayout = UIRectEdgeNone;
但是下面的tabbar的颜色就不对劲了，望标哥有空看看，好像是整体的self.view，已经没有在tabbar背面了。

**Comment by CoderJackyHuang** [comment]
这跟tabbar没有关系的啊，tabbar与self.view也没有关系的啊

**Comment by smileat** [comment]
是我自己知识不够，谢谢标哥抽空指教。这个可以关掉了=。=
