### ISSUE TITLE
能添加点击事件吗

### ISSUE THREAD

**Issue by youzi001** [CoderJackyHuang/HYBLoopScrollView#21]

**Comment by CoderJackyHuang** [comment]
这不是有点击事件吗？onSelected参数就是回调！

原始邮件
发件人:柚子notifications@github.com
收件人:CoderJackyHuang/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
发送时间:2016年5月24日(周二) 19:14
主题:[CoderJackyHuang/HYBLoopScrollView] 能添加点击事件吗 (#21)

**Comment by youzi001** [comment]
谢谢啊 知道了 

------------------ 原始邮件 ------------------
发件人: "JackyHuang";notifications@github.com;
发送时间: 2016年5月25日(星期三) 上午9:37
收件人: "CoderJackyHuang/HYBLoopScrollView"HYBLoopScrollView@noreply.github.com; 
抄送: "Autistic"474398335@qq.com; "Author"author@noreply.github.com; 
主题: Re: [CoderJackyHuang/HYBLoopScrollView] 能添加点击事件吗 (#21)

这不是有点击事件吗？onSelected参数就是回调！

 原始邮件
 发件人:柚子notifications@github.com
 收件人:CoderJackyHuang/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
 发送时间:2016年5月24日(周二) 19:14
 主题:[CoderJackyHuang/HYBLoopScrollView] 能添加点击事件吗 (#21)
