### ISSUE TITLE
在swift中不能创建出来对象呀 是怎么回事?

### ISSUE THREAD

**Issue by LoSenTrad** [CoderJackyHuang/HYBLoopScrollView#22]
今天项目用到了 轮播器   但是使用的时候是不能创建出来  是不是不能再swift中使用啊     及时那个Loop类方法不能使用   pod也不行   点进去xcode内部查看这个框架的代码  及时没有这个类方法   不知道是什么问题  这个框架是标哥的?啊哈哈

**Comment by CoderJackyHuang** [comment]
没在Swift中使用过，不过Swift应该是可以直接使用的啊。

原始邮件
发件人:ShengQiangLuonotifications@github.com
收件人:CoderJackyHuang/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
发送时间:2016年6月5日(周日) 02:36
主题:[CoderJackyHuang/HYBLoopScrollView] 在swift中不能创建出来对象呀 是怎么回事? (#22)

今天项目用到了 轮播器 但是使用的时候是不能创建出来 是不是不能再swift中使用啊 及时那个Loop类方法不能使用 pod也不行 点进去xcode内部查看这个框架的代码 及时没有这个类方法 不知道是什么问题 这个框架是标哥的?啊哈哈
