### ISSUE TITLE
网络加载多张图时图片乱掉

### ISSUE THREAD

**Issue by zhangyandong** [CoderJackyHuang/HYBLoopScrollView#3]
网络加载多张图时，后面会显示前面已经加载的图片，网络慢或图片大的情况下很容易出现，应该是网络异步加载完一张图片后，刚好滚动到下一张时，会把上一张加载的图片带过来

**Comment by CoderJackyHuang** [comment]
谢谢您的反馈，我会在业余时间尽快修复！！
再次感谢！！

原始邮件
发件人:张艳东notifications@github.com
收件人:632840804/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
发送时间:2015年7月24日(周五) 11:05
主题:[HYBLoopScrollView] 网络加载多张图时图片乱掉 (#3)

网络加载多张图时，后面会显示前面已经加载的图片，网络慢或图片大的情况下很容易出现
