### ISSUE TITLE
怎么刷新

### ISSUE THREAD

**Issue by xinqidian** [CoderJackyHuang/HYBLoopScrollView#4]
如果页面刷新 这个怎么刷新

**Comment by CoderJackyHuang** [comment]
您是指重新加载所有的图片吗？如果是，您只需要修改其URL即可。当定时器时间到达时，会自动切换到下一张图片，这时候会自动判断是否已经加载有，如果没有则会自动异步去获取图片数据。

如果您是指页面要将这套控件移除然后再重新创建一套，那么也是可以的。只要刷新数据源就可以了

**Comment by xinqidian** [comment]
谢谢  明白了  非常感谢

------------------ 原始邮件 ------------------
发件人: "JackyHuang";notifications@github.com;
发送时间: 2015年11月23日(星期一) 晚上7:53
收件人: "CoderJackyHuang/HYBLoopScrollView"HYBLoopScrollView@noreply.github.com; 
抄送: "木"1174762990@qq.com; 
主题: Re: [HYBLoopScrollView] 怎么刷新 (#4)

您是指重新加载所有的图片吗？如果是，您只需要修改其URL即可。当定时器时间到达时，会自动切换到下一张图片，这时候会自动判断是否已经加载有，如果没有则会自动异步去获取图片数据。

如果您是指页面要将这套控件移除然后再重新创建一套，那么也是可以的。只要刷新数据源就可以了

**Comment by smileat** [comment]
刷新数据源weakSelf.loop.imageUrls = imageUrlArray;或者[weakSelf.loop setImageUrls:imageUrlArray];之前，必须要把weakSelf.loop.imageUrls先设置为nil，否则就崩溃。
