### ISSUE TITLE
标哥，貌似设置滚动时间 不怎么管用

### ISSUE THREAD

**Issue by xinqidian** [CoderJackyHuang/HYBLoopScrollView#5]
还有设置  暂停滚动后  手动滑动一下  会自动滚动一个图片  看过你的博客  表示感谢！！！！

**Comment by CoderJackyHuang** [comment]
if (self.timer != nil) {
  [self startTimer];
  return;
 }

第156行这里，由于fix之前的bug所导致了这个bug，将self startTimer这行注释掉试试

原始邮件
发件人:xinqidiannotifications@github.com
收件人:CoderJackyHuang/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
发送时间:2015年12月7日(周一) 10:04
主题:[HYBLoopScrollView] 标哥，貌似设置滚动时间 不怎么管用 (#5)

还有设置 暂停滚动后 手动滑动一下 会自动滚动一个图片 看过你的博客 表示感谢！！！！

**Comment by xinqidian** [comment]
恩 可以了

**Comment by CoderJackyHuang** [comment]
好的，谢谢反馈！！

原始邮件
发件人:xinqidiannotifications@github.com
收件人:CoderJackyHuang/HYBLoopScrollViewHYBLoopScrollView@noreply.github.com
抄送:JackyHuang18675574495@163.com
发送时间:2015年12月7日(周一) 10:15
主题:Re: [HYBLoopScrollView] 标哥，貌似设置滚动时间 不怎么管用 (#5)

恩 可以了
